export const data=[
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "NORTH DELHI_OR",
        "TM HQ": "NORTH DELHI",
        "TM ID": "114534",
        "TM Name": "Ajay Kumar",
        "Month": "Oct-23",
        "DRCODE": "13084405",
        "MSL CODE": "CIP608562",
        "DRNAME": "ANUPAM  PRAKASH",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "B",
        "SKU CODE": "32030920",
        "SKU Name": "NINTIB 100  MG CAPSULES 1 X 10 S",
        "BRAND": "NINTIB",
        "Qty": "1",
        "Value": "468",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "NORTH DELHI_OR",
        "TM HQ": "NORTH DELHI",
        "TM ID": "114534",
        "TM Name": "Ajay Kumar",
        "Month": "Nov-23",
        "DRCODE": "13084405",
        "MSL CODE": "CIP608562",
        "DRNAME": "ANUPAM  PRAKASH",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "B",
        "SKU CODE": "32030981",
        "SKU Name": "NINTIB 150 MG CAPSULES  1 X 10 S",
        "BRAND": "NINTIB",
        "Qty": "1",
        "Value": "574",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "NORTH DELHI_OR",
        "TM HQ": "NORTH DELHI",
        "TM ID": "114534",
        "TM Name": "Ajay Kumar",
        "Month": "Nov-23",
        "DRCODE": "13084405",
        "MSL CODE": "CIP608562",
        "DRNAME": "ANUPAM  PRAKASH",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "B",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "10",
        "Value": "2,150",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "NORTH DELHI_OR",
        "TM HQ": "NORTH DELHI",
        "TM ID": "114534",
        "TM Name": "Ajay Kumar",
        "Month": "Nov-23",
        "DRCODE": "13084425",
        "MSL CODE": "CLX01575182",
        "DRNAME": "ANIL  CHAUDHARY",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "A",
        "SKU CODE": "32007170",
        "SKU Name": "FURAMIST AZ NASAL SP",
        "BRAND": "Furamist",
        "Qty": "10",
        "Value": "2,991",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "NORTH DELHI_OR",
        "TM HQ": "NORTH DELHI",
        "TM ID": "114534",
        "TM Name": "Ajay Kumar",
        "Month": "Nov-23",
        "DRCODE": "13084425",
        "MSL CODE": "CLX01575182",
        "DRNAME": "ANIL  CHAUDHARY",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "A",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "30",
        "Value": "6,449",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Above 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "NORTH DELHI_OR",
        "TM HQ": "NORTH DELHI",
        "TM ID": "114534",
        "TM Name": "Ajay Kumar",
        "Month": "Nov-23",
        "DRCODE": "13084425",
        "MSL CODE": "CLX01575182",
        "DRNAME": "ANIL  CHAUDHARY",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "A",
        "SKU CODE": "32034960",
        "SKU Name": "ABLung-N Tablet",
        "BRAND": "Ablung",
        "Qty": "10",
        "Value": "1,348",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "NORTH DELHI_OR",
        "TM HQ": "NORTH DELHI",
        "TM ID": "114534",
        "TM Name": "Ajay Kumar",
        "Month": "Nov-23",
        "DRCODE": "13084434",
        "MSL CODE": "CIP4837538",
        "DRNAME": "RAKESH  MAURYA",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "B",
        "SKU CODE": "32030981",
        "SKU Name": "NINTIB 150 MG CAPSULES  1 X 10 S",
        "BRAND": "NINTIB",
        "Qty": "3",
        "Value": "1,721",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "NORTH DELHI_OR",
        "TM HQ": "NORTH DELHI",
        "TM ID": "114534",
        "TM Name": "Ajay Kumar",
        "Month": "Nov-23",
        "DRCODE": "13084434",
        "MSL CODE": "CIP4837538",
        "DRNAME": "RAKESH  MAURYA",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "B",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "20",
        "Value": "4,299",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "NORTH DELHI_OR",
        "TM HQ": "NORTH DELHI",
        "TM ID": "114534",
        "TM Name": "Ajay Kumar",
        "Month": "Nov-23",
        "DRCODE": "13084434",
        "MSL CODE": "CIP4837538",
        "DRNAME": "RAKESH  MAURYA",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "B",
        "SKU CODE": "32029065",
        "SKU Name": "ABlung SR 200mg",
        "BRAND": "Ablung",
        "Qty": "10",
        "Value": "1,457",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "NORTH DELHI_OR",
        "TM HQ": "NORTH DELHI",
        "TM ID": "114534",
        "TM Name": "Ajay Kumar",
        "Month": "Nov-23",
        "DRCODE": "13084434",
        "MSL CODE": "CIP4837538",
        "DRNAME": "RAKESH  MAURYA",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "B",
        "SKU CODE": "32034960",
        "SKU Name": "ABLung-N Tablet",
        "BRAND": "Ablung",
        "Qty": "5",
        "Value": "674",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "NORTH DELHI_OR",
        "TM HQ": "NORTH DELHI",
        "TM ID": "114534",
        "TM Name": "Ajay Kumar",
        "Month": "Nov-23",
        "DRCODE": "13084453",
        "MSL CODE": "CLX0969245",
        "DRNAME": "B K MENON",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "B",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "10",
        "Value": "2,150",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "NORTH DELHI_OR",
        "TM HQ": "NORTH DELHI",
        "TM ID": "114534",
        "TM Name": "Ajay Kumar",
        "Month": "Nov-23",
        "DRCODE": "13084455",
        "MSL CODE": "CIP4828625",
        "DRNAME": "SHARMISTHA  DUTTA",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "B",
        "SKU CODE": "32030920",
        "SKU Name": "NINTIB 100  MG CAPSULES 1 X 10 S",
        "BRAND": "NINTIB",
        "Qty": "1",
        "Value": "468",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "NORTH DELHI_OR",
        "TM HQ": "NORTH DELHI",
        "TM ID": "114534",
        "TM Name": "Ajay Kumar",
        "Month": "Nov-23",
        "DRCODE": "13084455",
        "MSL CODE": "CIP4828625",
        "DRNAME": "SHARMISTHA  DUTTA",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "B",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "20",
        "Value": "4,299",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "NORTH DELHI_OR",
        "TM HQ": "NORTH DELHI",
        "TM ID": "114534",
        "TM Name": "Ajay Kumar",
        "Month": "Nov-23",
        "DRCODE": "13084457",
        "MSL CODE": "CIR1529",
        "DRNAME": "PARUL  MRIGPURI",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "B",
        "SKU CODE": "32030981",
        "SKU Name": "NINTIB 150 MG CAPSULES  1 X 10 S",
        "BRAND": "NINTIB",
        "Qty": "2",
        "Value": "1,147",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "NORTH DELHI_OR",
        "TM HQ": "NORTH DELHI",
        "TM ID": "114534",
        "TM Name": "Ajay Kumar",
        "Month": "Nov-23",
        "DRCODE": "13084457",
        "MSL CODE": "CIR1529",
        "DRNAME": "PARUL  MRIGPURI",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "B",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "25",
        "Value": "5,374",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Above 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "NORTH DELHI_OR",
        "TM HQ": "NORTH DELHI",
        "TM ID": "114534",
        "TM Name": "Ajay Kumar",
        "Month": "Nov-23",
        "DRCODE": "13084495",
        "MSL CODE": "CIW967748",
        "DRNAME": "SONAL  CHOREY",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "B",
        "SKU CODE": "32029609",
        "SKU Name": "MONTAIR-10 TABLETS 1 X 15 S IP",
        "BRAND": "Montair",
        "Qty": "10",
        "Value": "1,595",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "NORTH DELHI_OR",
        "TM HQ": "NORTH DELHI",
        "TM ID": "114534",
        "TM Name": "Ajay Kumar",
        "Month": "Nov-23",
        "DRCODE": "13084495",
        "MSL CODE": "CIW967748",
        "DRNAME": "SONAL  CHOREY",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "B",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "15",
        "Value": "3,224",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "NORTH DELHI_OR",
        "TM HQ": "NORTH DELHI",
        "TM ID": "114534",
        "TM Name": "Ajay Kumar",
        "Month": "Nov-23",
        "DRCODE": "13084495",
        "MSL CODE": "CIW967748",
        "DRNAME": "SONAL  CHOREY",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "B",
        "SKU CODE": "32029065",
        "SKU Name": "ABlung SR 200mg",
        "BRAND": "Ablung",
        "Qty": "10",
        "Value": "1,457",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "NORTH DELHI_OR",
        "TM HQ": "NORTH DELHI",
        "TM ID": "114534",
        "TM Name": "Ajay Kumar",
        "Month": "Nov-23",
        "DRCODE": "13084497",
        "MSL CODE": "CLX01331854",
        "DRNAME": "SHYAM MOHAN NAYAK",
        "SPECIALTY": "CONSULTANT PHYSICIAN",
        "Spl": "CP",
        "Class": "B",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "25",
        "Value": "5,374",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Above 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "NORTH DELHI_OR",
        "TM HQ": "NORTH DELHI",
        "TM ID": "114534",
        "TM Name": "Ajay Kumar",
        "Month": "Nov-23",
        "DRCODE": "13084497",
        "MSL CODE": "CLX01331854",
        "DRNAME": "SHYAM MOHAN NAYAK",
        "SPECIALTY": "CONSULTANT PHYSICIAN",
        "Spl": "CP",
        "Class": "B",
        "SKU CODE": "32034960",
        "SKU Name": "ABLung-N Tablet",
        "BRAND": "Ablung",
        "Qty": "10",
        "Value": "1,348",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "NORTH DELHI_OR",
        "TM HQ": "NORTH DELHI",
        "TM ID": "114534",
        "TM Name": "Ajay Kumar",
        "Month": "Nov-23",
        "DRCODE": "13084513",
        "MSL CODE": "CLX0359573",
        "DRNAME": "NITIN  GOEL",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "B",
        "SKU CODE": "32007170",
        "SKU Name": "FURAMIST AZ NASAL SP",
        "BRAND": "Furamist",
        "Qty": "5",
        "Value": "1,495",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "NORTH DELHI_OR",
        "TM HQ": "NORTH DELHI",
        "TM ID": "114534",
        "TM Name": "Ajay Kumar",
        "Month": "Nov-23",
        "DRCODE": "13084513",
        "MSL CODE": "CLX0359573",
        "DRNAME": "NITIN  GOEL",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "B",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "20",
        "Value": "4,299",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "NORTH DELHI_OR",
        "TM HQ": "NORTH DELHI",
        "TM ID": "114534",
        "TM Name": "Ajay Kumar",
        "Month": "Nov-23",
        "DRCODE": "13105158",
        "MSL CODE": "CIR20686",
        "DRNAME": "N C Bhatt",
        "SPECIALTY": "CONSULTANT PHYSICIAN",
        "Spl": "CP",
        "Class": "B",
        "SKU CODE": "32007170",
        "SKU Name": "FURAMIST AZ NASAL SP",
        "BRAND": "Furamist",
        "Qty": "5",
        "Value": "1,495",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "NORTH DELHI_OR",
        "TM HQ": "NORTH DELHI",
        "TM ID": "114534",
        "TM Name": "Ajay Kumar",
        "Month": "Nov-23",
        "DRCODE": "13105158",
        "MSL CODE": "CIR20686",
        "DRNAME": "N C Bhatt",
        "SPECIALTY": "CONSULTANT PHYSICIAN",
        "Spl": "CP",
        "Class": "B",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "10",
        "Value": "2,150",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "NORTH DELHI_OR",
        "TM HQ": "NORTH DELHI",
        "TM ID": "114534",
        "TM Name": "Ajay Kumar",
        "Month": "Nov-23",
        "DRCODE": "13105183",
        "MSL CODE": "CLX309662",
        "DRNAME": "Rajeev  Goyal",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "B",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "15",
        "Value": "3,224",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "NORTH DELHI_OR",
        "TM HQ": "NORTH DELHI",
        "TM ID": "114534",
        "TM Name": "Ajay Kumar",
        "Month": "Nov-23",
        "DRCODE": "13105183",
        "MSL CODE": "CLX309662",
        "DRNAME": "Rajeev  Goyal",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "B",
        "SKU CODE": "32029065",
        "SKU Name": "ABlung SR 200mg",
        "BRAND": "Ablung",
        "Qty": "10",
        "Value": "1,457",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "NORTH DELHI_OR",
        "TM HQ": "NORTH DELHI",
        "TM ID": "114534",
        "TM Name": "Ajay Kumar",
        "Month": "Nov-23",
        "DRCODE": "13105630",
        "MSL CODE": "CLX1486501",
        "DRNAME": "Chetan  Rijwani",
        "SPECIALTY": "GENERAL PHYSICIAN",
        "Spl": "GP",
        "Class": "B",
        "SKU CODE": "32019722",
        "SKU Name": "MONTAIR 5MG 15 TAB",
        "BRAND": "Montair",
        "Qty": "10",
        "Value": "1,190",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "NORTH DELHI_OR",
        "TM HQ": "NORTH DELHI",
        "TM ID": "114534",
        "TM Name": "Ajay Kumar",
        "Month": "Nov-23",
        "DRCODE": "13105630",
        "MSL CODE": "CLX1486501",
        "DRNAME": "Chetan  Rijwani",
        "SPECIALTY": "GENERAL PHYSICIAN",
        "Spl": "GP",
        "Class": "B",
        "SKU CODE": "32005839",
        "SKU Name": "MONTAIR LC KID SYP",
        "BRAND": "Montair LC Kids",
        "Qty": "20",
        "Value": "1,559",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "NORTH DELHI_OR",
        "TM HQ": "NORTH DELHI",
        "TM ID": "114534",
        "TM Name": "Ajay Kumar",
        "Month": "Nov-23",
        "DRCODE": "13105632",
        "MSL CODE": "CLX0353106",
        "DRNAME": "Naveen  Jain",
        "SPECIALTY": "PAEDIATRICIAN",
        "Spl": "Paed",
        "Class": "B",
        "SKU CODE": "32005839",
        "SKU Name": "MONTAIR LC KID SYP",
        "BRAND": "Montair LC Kids",
        "Qty": "25",
        "Value": "1,948",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "NORTH DELHI_OR",
        "TM HQ": "NORTH DELHI",
        "TM ID": "114534",
        "TM Name": "Ajay Kumar",
        "Month": "Nov-23",
        "DRCODE": "13105635",
        "MSL CODE": "CIP38120",
        "DRNAME": "Sanjeev  Madan",
        "SPECIALTY": "CONSULTANT PHYSICIAN",
        "Spl": "CP",
        "Class": "B",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "20",
        "Value": "4,299",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "NORTH DELHI_OR",
        "TM HQ": "NORTH DELHI",
        "TM ID": "114534",
        "TM Name": "Ajay Kumar",
        "Month": "Nov-23",
        "DRCODE": "13889584",
        "MSL CODE": "CLX0755724",
        "DRNAME": "Pooja  Kumari",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "B",
        "SKU CODE": "32030920",
        "SKU Name": "NINTIB 100  MG CAPSULES 1 X 10 S",
        "BRAND": "NINTIB",
        "Qty": "2",
        "Value": "936",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "NORTH DELHI_OR",
        "TM HQ": "NORTH DELHI",
        "TM ID": "114534",
        "TM Name": "Ajay Kumar",
        "Month": "Nov-23",
        "DRCODE": "13889584",
        "MSL CODE": "CLX0755724",
        "DRNAME": "Pooja  Kumari",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "B",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "24",
        "Value": "5,159",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Above 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9199625",
        "MSL CODE": "CLX0444518",
        "DRNAME": "M K  GUPTA",
        "SPECIALTY": "CONSULTANT PHYSICIAN",
        "Spl": "CP",
        "Class": "B",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "20",
        "Value": "4,299",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9199664",
        "MSL CODE": "CIP294457",
        "DRNAME": "YOGESH  JAIN",
        "SPECIALTY": "ENT SURGEON",
        "Spl": "ENT",
        "Class": "B",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "20",
        "Value": "4,299",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9199666",
        "MSL CODE": "CLX01221554",
        "DRNAME": "MANU  SHARMA",
        "SPECIALTY": "GENERAL PHYSICIAN",
        "Spl": "GP",
        "Class": "B",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "20",
        "Value": "4,299",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9199667",
        "MSL CODE": "CLX01100026",
        "DRNAME": "NADEEM  AHMED",
        "SPECIALTY": "GENERAL PHYSICIAN",
        "Spl": "GP",
        "Class": "B",
        "SKU CODE": "32016819",
        "SKU Name": "LEVOLIN PLUS SYRUP 100 ML",
        "BRAND": "Levolin Plus",
        "Qty": "10",
        "Value": "564",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9199667",
        "MSL CODE": "CLX01100026",
        "DRNAME": "NADEEM  AHMED",
        "SPECIALTY": "GENERAL PHYSICIAN",
        "Spl": "GP",
        "Class": "B",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "35",
        "Value": "7,524",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Above 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9199669",
        "MSL CODE": "CLX0993897",
        "DRNAME": "SANJIV  DANG",
        "SPECIALTY": "GENERAL PHYSICIAN",
        "Spl": "GP",
        "Class": "B",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "10",
        "Value": "2,150",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9199682",
        "MSL CODE": "CLX0648624",
        "DRNAME": "AMIT  MAJUMDAR",
        "SPECIALTY": "CONSULTANT PHYSICIAN",
        "Spl": "CP",
        "Class": "B",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "4",
        "Value": "860",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9200005",
        "MSL CODE": "CLX62199",
        "DRNAME": "KIRAN  BHALLA",
        "SPECIALTY": "ENT SURGEON",
        "Spl": "ENT",
        "Class": "B",
        "SKU CODE": "32032425",
        "SKU Name": "FURAMIST",
        "BRAND": "Furamist",
        "Qty": "2",
        "Value": "443",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9200005",
        "MSL CODE": "CLX62199",
        "DRNAME": "KIRAN  BHALLA",
        "SPECIALTY": "ENT SURGEON",
        "Spl": "ENT",
        "Class": "B",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "20",
        "Value": "4,299",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9200040",
        "MSL CODE": "CIP892754",
        "DRNAME": "ANKUR  GUPTA",
        "SPECIALTY": "CONSULTANT PHYSICIAN",
        "Spl": "CP",
        "Class": "B",
        "SKU CODE": "32029609",
        "SKU Name": "MONTAIR-10 TABLETS 1 X 15 S IP",
        "BRAND": "Montair",
        "Qty": "10",
        "Value": "1,595",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9200040",
        "MSL CODE": "CIP892754",
        "DRNAME": "ANKUR  GUPTA",
        "SPECIALTY": "CONSULTANT PHYSICIAN",
        "Spl": "CP",
        "Class": "B",
        "SKU CODE": "32032425",
        "SKU Name": "FURAMIST",
        "BRAND": "Furamist",
        "Qty": "5",
        "Value": "1,107",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9200040",
        "MSL CODE": "CIP892754",
        "DRNAME": "ANKUR  GUPTA",
        "SPECIALTY": "CONSULTANT PHYSICIAN",
        "Spl": "CP",
        "Class": "B",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "40",
        "Value": "8,598",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Above 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9200050",
        "MSL CODE": "CLX0304083",
        "DRNAME": "Y C C PAUL",
        "SPECIALTY": "CONSULTANT PHYSICIAN",
        "Spl": "CP",
        "Class": "B",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "13",
        "Value": "2,794",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9200064",
        "MSL CODE": "CLX0913689",
        "DRNAME": "ZEENAT  SULTANA",
        "SPECIALTY": "ENT SURGEON",
        "Spl": "ENT",
        "Class": "A",
        "SKU CODE": "32007170",
        "SKU Name": "FURAMIST AZ NASAL SP",
        "BRAND": "Furamist",
        "Qty": "11",
        "Value": "3,290",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9200064",
        "MSL CODE": "CLX0913689",
        "DRNAME": "ZEENAT  SULTANA",
        "SPECIALTY": "ENT SURGEON",
        "Spl": "ENT",
        "Class": "A",
        "SKU CODE": "32032425",
        "SKU Name": "FURAMIST",
        "BRAND": "Furamist",
        "Qty": "6",
        "Value": "1,329",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9200064",
        "MSL CODE": "CLX0913689",
        "DRNAME": "ZEENAT  SULTANA",
        "SPECIALTY": "ENT SURGEON",
        "Spl": "ENT",
        "Class": "A",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "40",
        "Value": "8,598",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Above 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9200066",
        "MSL CODE": "CLX01429089",
        "DRNAME": "MALIK  ISLAHUDDIN",
        "SPECIALTY": "ENT SURGEON",
        "Spl": "ENT",
        "Class": "B",
        "SKU CODE": "32007170",
        "SKU Name": "FURAMIST AZ NASAL SP",
        "BRAND": "Furamist",
        "Qty": "8",
        "Value": "2,393",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9200066",
        "MSL CODE": "CLX01429089",
        "DRNAME": "MALIK  ISLAHUDDIN",
        "SPECIALTY": "ENT SURGEON",
        "Spl": "ENT",
        "Class": "B",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "30",
        "Value": "6,449",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Above 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9200069",
        "MSL CODE": "CIP706592",
        "DRNAME": "ABHISHEK  BHUSHAN",
        "SPECIALTY": "ENT SURGEON",
        "Spl": "ENT",
        "Class": "B",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "25",
        "Value": "5,374",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Above 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9200089",
        "MSL CODE": "CIP794731",
        "DRNAME": "ANWAR  HABIB",
        "SPECIALTY": "CONSULTANT PHYSICIAN",
        "Spl": "CP",
        "Class": "B",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "5",
        "Value": "1,075",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9200095",
        "MSL CODE": "CLX0891001",
        "DRNAME": "M H  KHAN",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "A",
        "SKU CODE": "32029609",
        "SKU Name": "MONTAIR-10 TABLETS 1 X 15 S IP",
        "BRAND": "Montair",
        "Qty": "10",
        "Value": "1,595",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9200095",
        "MSL CODE": "CLX0891001",
        "DRNAME": "M H  KHAN",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "A",
        "SKU CODE": "32032425",
        "SKU Name": "FURAMIST",
        "BRAND": "Furamist",
        "Qty": "6",
        "Value": "1,329",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9200095",
        "MSL CODE": "CLX0891001",
        "DRNAME": "M H  KHAN",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "A",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "50",
        "Value": "10,748",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Above 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9200095",
        "MSL CODE": "CLX0891001",
        "DRNAME": "M H  KHAN",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "A",
        "SKU CODE": "32034960",
        "SKU Name": "ABLung-N Tablet",
        "BRAND": "Ablung",
        "Qty": "6",
        "Value": "809",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9200097",
        "MSL CODE": "CLX0317602",
        "DRNAME": "VED  PRAKASH",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "A Plus",
        "SKU CODE": "32007170",
        "SKU Name": "FURAMIST AZ NASAL SP",
        "BRAND": "Furamist",
        "Qty": "11",
        "Value": "3,290",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9200097",
        "MSL CODE": "CLX0317602",
        "DRNAME": "VED  PRAKASH",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "A Plus",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "100",
        "Value": "21,496",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Above 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9200097",
        "MSL CODE": "CLX0317602",
        "DRNAME": "VED  PRAKASH",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "A Plus",
        "SKU CODE": "32034960",
        "SKU Name": "ABLung-N Tablet",
        "BRAND": "Ablung",
        "Qty": "20",
        "Value": "2,696",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9200098",
        "MSL CODE": "CIP294502",
        "DRNAME": "T K  CHAKRABORTY",
        "SPECIALTY": "CONSULTANT PHYSICIAN",
        "Spl": "CP",
        "Class": "B",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "28",
        "Value": "6,019",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Above 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9200105",
        "MSL CODE": "CLX0889340",
        "DRNAME": "SUNIL  MAHESWARI",
        "SPECIALTY": "CONSULTANT PHYSICIAN",
        "Spl": "CP",
        "Class": "B",
        "SKU CODE": "32007170",
        "SKU Name": "FURAMIST AZ NASAL SP",
        "BRAND": "Furamist",
        "Qty": "1",
        "Value": "299",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9200105",
        "MSL CODE": "CLX0889340",
        "DRNAME": "SUNIL  MAHESWARI",
        "SPECIALTY": "CONSULTANT PHYSICIAN",
        "Spl": "CP",
        "Class": "B",
        "SKU CODE": "32029609",
        "SKU Name": "MONTAIR-10 TABLETS 1 X 15 S IP",
        "BRAND": "Montair",
        "Qty": "1",
        "Value": "159",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9200105",
        "MSL CODE": "CLX0889340",
        "DRNAME": "SUNIL  MAHESWARI",
        "SPECIALTY": "CONSULTANT PHYSICIAN",
        "Spl": "CP",
        "Class": "B",
        "SKU CODE": "32019722",
        "SKU Name": "MONTAIR 5MG 15 TAB",
        "BRAND": "Montair",
        "Qty": "1",
        "Value": "119",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9200105",
        "MSL CODE": "CLX0889340",
        "DRNAME": "SUNIL  MAHESWARI",
        "SPECIALTY": "CONSULTANT PHYSICIAN",
        "Spl": "CP",
        "Class": "B",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "12",
        "Value": "2,580",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Oct-23",
        "DRCODE": "9240094",
        "MSL CODE": "CLX0735759",
        "DRNAME": "SANJEEV  ZUTSHI",
        "SPECIALTY": "CONSULTANT PHYSICIAN",
        "Spl": "CP",
        "Class": "B",
        "SKU CODE": "32032425",
        "SKU Name": "FURAMIST",
        "BRAND": "Furamist",
        "Qty": "9",
        "Value": "1,993",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "9240094",
        "MSL CODE": "CLX0735759",
        "DRNAME": "SANJEEV  ZUTSHI",
        "SPECIALTY": "CONSULTANT PHYSICIAN",
        "Spl": "CP",
        "Class": "B",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "60",
        "Value": "12,898",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Above 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Oct-23",
        "DRCODE": "9241291",
        "MSL CODE": "CLX0630027",
        "DRNAME": "M S RAWAT",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "B",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "20",
        "Value": "4,299",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "10194040",
        "MSL CODE": "CIR64945",
        "DRNAME": "AZMAT  KARIM",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "A Plus",
        "SKU CODE": "32007170",
        "SKU Name": "FURAMIST AZ NASAL SP",
        "BRAND": "Furamist",
        "Qty": "12",
        "Value": "3,589",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "10194040",
        "MSL CODE": "CIR64945",
        "DRNAME": "AZMAT  KARIM",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "A Plus",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "280",
        "Value": "60,189",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Above 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "10199141",
        "MSL CODE": "CLX01280447",
        "DRNAME": "SHAMSHEER  AKHTAR",
        "SPECIALTY": "PAEDIATRICIAN",
        "Spl": "Paed",
        "Class": "B",
        "SKU CODE": "32005839",
        "SKU Name": "MONTAIR LC KID SYP",
        "BRAND": "Montair LC Kids",
        "Qty": "30",
        "Value": "2,338",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "10199141",
        "MSL CODE": "CLX01280447",
        "DRNAME": "SHAMSHEER  AKHTAR",
        "SPECIALTY": "PAEDIATRICIAN",
        "Spl": "Paed",
        "Class": "B",
        "SKU CODE": "32016819",
        "SKU Name": "LEVOLIN PLUS SYRUP 100 ML",
        "BRAND": "Levolin Plus",
        "Qty": "25",
        "Value": "1,409",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "10199141",
        "MSL CODE": "CLX01280447",
        "DRNAME": "SHAMSHEER  AKHTAR",
        "SPECIALTY": "PAEDIATRICIAN",
        "Spl": "Paed",
        "Class": "B",
        "SKU CODE": "32029685",
        "SKU Name": "MONTAIR LC KID TAB",
        "BRAND": "Montair LC Kids",
        "Qty": "10",
        "Value": "747",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "10199154",
        "MSL CODE": "CLX01486686",
        "DRNAME": "SHALIQ  RAJA",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "B",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "10",
        "Value": "2,150",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "10199182",
        "MSL CODE": "CIP889003",
        "DRNAME": "ABUL  FAIZ",
        "SPECIALTY": "CONSULTANT PHYSICIAN",
        "Spl": "CP",
        "Class": "B",
        "SKU CODE": "32007170",
        "SKU Name": "FURAMIST AZ NASAL SP",
        "BRAND": "Furamist",
        "Qty": "5",
        "Value": "1,495",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Oct-23",
        "DRCODE": "10199182",
        "MSL CODE": "CIP889003",
        "DRNAME": "ABUL  FAIZ",
        "SPECIALTY": "CONSULTANT PHYSICIAN",
        "Spl": "CP",
        "Class": "B",
        "SKU CODE": "32032425",
        "SKU Name": "FURAMIST",
        "BRAND": "Furamist",
        "Qty": "6",
        "Value": "1,329",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "10199182",
        "MSL CODE": "CIP889003",
        "DRNAME": "ABUL  FAIZ",
        "SPECIALTY": "CONSULTANT PHYSICIAN",
        "Spl": "CP",
        "Class": "B",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "35",
        "Value": "7,524",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Above 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "10199270",
        "MSL CODE": "CIP794992",
        "DRNAME": "R N PRASAD",
        "SPECIALTY": "CONSULTANT PHYSICIAN",
        "Spl": "CP",
        "Class": "B",
        "SKU CODE": "32029633",
        "SKU Name": "MONTAIR LC 15 TAB",
        "BRAND": "Montair LC Adult",
        "Qty": "22",
        "Value": "4,729",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "10199338",
        "MSL CODE": "CLX0506943",
        "DRNAME": "P V TYAGI",
        "SPECIALTY": "PAEDIATRICIAN",
        "Spl": "Paed",
        "Class": "B",
        "SKU CODE": "32005839",
        "SKU Name": "MONTAIR LC KID SYP",
        "BRAND": "Montair LC Kids",
        "Qty": "40",
        "Value": "3,117",
        "Segment Leadership": "Yes",
        "Status 2k": "Above 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Nov-23",
        "DRCODE": "10199338",
        "MSL CODE": "CLX0506943",
        "DRNAME": "P V TYAGI",
        "SPECIALTY": "PAEDIATRICIAN",
        "Spl": "Paed",
        "Class": "B",
        "SKU CODE": "32016819",
        "SKU Name": "LEVOLIN PLUS SYRUP 100 ML",
        "BRAND": "Levolin Plus",
        "Qty": "23",
        "Value": "1,296",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    },
    {
        "BU": "Respiratory Orals",
        "TASKFORCE": "Team 4 (OR)",
        "ZMHQ": "DELHI_OR",
        "RMHQ": "DELHI_OR",
        "ABM HQ": "SOUTH DELHI_OR",
        "TM HQ": "SOUTH DELHI",
        "TM ID": "111959",
        "TM Name": "Ajay Chaudhary",
        "Month": "Oct-23",
        "DRCODE": "10199355",
        "MSL CODE": "CLX0790915",
        "DRNAME": "M  SHAMSHAD",
        "SPECIALTY": "CHEST PHYSICIAN",
        "Spl": "Chest",
        "Class": "B",
        "SKU CODE": "32029609",
        "SKU Name": "MONTAIR-10 TABLETS 1 X 15 S IP",
        "BRAND": "Montair",
        "Qty": "10",
        "Value": "1,595",
        "Segment Leadership": "Yes",
        "Status 2k": "Below 2K",
        "Status 5k": "Below 5k"
    }
]